### ISSUE TITLE
`testCreation` will fail on the first Sunday of October from 02:00 local time for 1 hour

### ISSUE THREAD

**Issue by micolous** [mithro/python-datetime-tz#9]
https://github.com/mithro/python-datetime-tz/blob/master/tests.py#L337

This test uses `datetime.datetime.now()` in order to populate a time value.  On the first Sunday of October each year, between 02:00:00 and 02:59:59 local time (not Sydney time), this test will fail with an error:

```
======================================================================
FAIL: testCreation (__main__.TestDatetimeTZ)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 342, in testCreation
    self.assertEqual(d4.tzinfo, d5.tzinfo)
AssertionError: <DstTzInfo 'Australia/Sydney' EST+10:00:00 STD> != <DstTzInfo 'Australia/Sydney' EST+11:00:00 DST>

----------------------------------------------------------------------
```

It looks like the library and pytz are making different assumptions about how to handle ambiguous times.  The function itself is dangerous (as is anything that depends on "now") because the tests are no longer deterministic.

This test won't ever fail for systems with the same DST transition time as Sydney, as `datetime.datetime.now()` will never return the ambiguous time value.  This means the test will fail if local time is set to Brisbane, Darwin or Perth time (no DST), but never fail if it is set to Adelaide, Hobart, Melbourne or Sydney time.

**Comment by mithro** [comment]
I fixed the date to use a static value.

The `def testBadDates` has some explicit tests for around how ambiguous times should be handled. 

```python
  def testBadDates(self):
    # For example, 1:30am on 27th Oct 2002 happened twice in the US/Eastern
    # timezone when the clocks where put back at the end of Daylight Savings
    # Time.
    # This could be 2002-10-27 01:30:00 EDT-0400
    #            or 2002-10-27 01:30:00 EST-0500
    loc_dt = datetime.datetime(2002, 10, 27, 1, 30, 00)
    self.assertRaises(pytz.AmbiguousTimeError, datetime_tz.datetime_tz,
                      loc_dt, pytz.timezone("US/Eastern"))

    # Check we can use is_dst to disambiguate.
    loc_dt = datetime.datetime(2002, 10, 27, 1, 30, 00)

    dt2 = datetime_tz.datetime_tz(
        loc_dt, pytz.timezone("US/Eastern"), is_dst=False)
    self.assertEqual(dt2.strftime(FMT), "2002-10-27 01:30:00 EST-0500")

    dt1 = datetime_tz.datetime_tz(
        loc_dt, pytz.timezone("US/Eastern"), is_dst=True)
    self.assertEqual(dt1.strftime(FMT), "2002-10-27 01:30:00 EDT-0400")

    # Similarly, 2:30am on 7th April 2002 never happened at all in the
    # US/Eastern timezone, as the clock where put forward at 2:00am skipping the
    # entire hour.
    loc_dt = datetime.datetime(2002, 4, 7, 2, 30, 00)

    raiseme = (pytz.AmbiguousTimeError, pytz.NonExistentTimeError)
    self.assertRaises(raiseme, datetime_tz.datetime_tz,
                      loc_dt, pytz.timezone("US/Eastern"))
    self.assertRaises(raiseme, datetime_tz.datetime_tz,
                      loc_dt, pytz.timezone("US/Eastern"), is_dst=True)
    self.assertRaises(raiseme, datetime_tz.datetime_tz,
                      loc_dt, pytz.timezone("US/Eastern"), is_dst=False)

    raiseme = (pytz.AmbiguousTimeError, pytz.NonExistentTimeError)
    self.assertRaises(raiseme, datetime_tz.datetime_tz,
                      loc_dt, pytz.timezone("US/Eastern"))
    self.assertRaises(raiseme, datetime_tz.datetime_tz,
                      loc_dt, pytz.timezone("US/Eastern"), is_dst=True)
    self.assertRaises(raiseme, datetime_tz.datetime_tz,
                      loc_dt, pytz.timezone("US/Eastern"), is_dst=False)
```

Are they examples of the above cases or do we need to extend the test cases here?

**Comment by mithro** [comment]
This should fail right? First Sunday of October this year is 4th?

```python
    # Testing....
    d4 = datetime.datetime(2015, 10, 4, 2, 30)
    d4 = pytz.timezone("Australia/Sydney").localize(d4)
    d5 = datetime_tz.datetime_tz(d4)
    self.assertTrue(isinstance(d3, datetime_tz.datetime_tz))
    self.assertTimezoneEqual(d4.tzinfo, d5.tzinfo)

    d4 = datetime.datetime(2015, 10, 4, 2, 30)
    d4 = pytz.timezone("Australia/Sydney").localize(d4)
    d5 = datetime_tz.datetime_tz(d4)
    self.assertTrue(isinstance(d3, datetime_tz.datetime_tz))
    self.assertTimezoneEqual(d4.tzinfo, d5.tzinfo)
```

**Comment by micolous** [comment]
That last test should fail.  I've got some code on my home computer that I used to induce the test failure, I'll go dig it up (but will be much later tonight).

It's not always failing with an exception (at the .localize call), but I have an old version of pytz on my home computer.

You can do `tz.localize(dt, is_dst=None)` and I think that forces it to throw an exception.

**Comment by mithro** [comment]
Ahh, I see what is happening, my assertTimezoneEqual is saying they are both the Australia/Sydney timezone.

The following repos;
```python
    # Testing....
    d4 = datetime.datetime(2015, 10, 4, 2, 30)
    d4 = pytz.timezone("Australia/Sydney").localize(d4, is_dst=True)
    d5 = datetime_tz.datetime_tz(d4)
    print d4, repr(d4)
    print d5, repr(d5)
    print
    self.assertTrue(isinstance(d3, datetime_tz.datetime_tz))
    self.assertTimezoneEqual(d4.tzinfo, d5.tzinfo)
    self.assertEqual(d4.tzinfo, d5.tzinfo)

    d4 = datetime.datetime(2015, 10, 4, 2, 30)
    d4 = pytz.timezone("Australia/Sydney").localize(d4, is_dst=False)
    d5 = datetime_tz.datetime_tz(d4)
    print d4, repr(d4)
    print d5, repr(d5)
    print
    self.assertTrue(isinstance(d3, datetime_tz.datetime_tz))
    self.assertTimezoneEqual(d4.tzinfo, d5.tzinfo)
    self.assertEqual(d4.tzinfo, d5.tzinfo)
```

```
2015-10-04 02:30:00+11:00 datetime.datetime(2015, 10, 4, 2, 30, tzinfo=<DstTzInfo 'Australia/Sydney' AEDT+11:00:00 DST>)
2015-10-04 01:30:00+10:00 datetime_tz(2015, 10, 4, 1, 30, tzinfo=<DstTzInfo 'Australia/Sydney' AEST+10:00:00 STD>)

F
======================================================================
FAIL: testCreation (__main__.TestDatetimeTZ)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 523, in testCreation
    self.assertEqual(d4.tzinfo, d5.tzinfo)
AssertionError: <DstTzInfo 'Australia/Sydney' AEDT+11:00:00 DST> != <DstTzInfo 'Australia/Sydney' AEST+10:00:00 STD>

----------------------------------------------------------------------
Ran 1 test in 0.174s

FAILED (failures=1)
```

**Comment by mithro** [comment]
So according to http://www.timeanddate.com/time/change/australia/sydney - 2:30am on October, 4th doesn't exist. Hence we should be getting an pytz.NonExistentTimeError()?

**Comment by mithro** [comment]
From the pytz documentation;

Similarly, 2:30am on 7th April 2002 never happened at all in the US/Eastern timezone, as the clocks where put forward at 2:00am skipping the entire hour:
```python
>>> dt = datetime(2002, 4, 7, 2, 30, 00)
>>> try:
...     eastern.localize(dt, is_dst=None)
... except pytz.exceptions.NonExistentTimeError:
...     print('pytz.exceptions.NonExistentTimeError: %s' % dt)
pytz.exceptions.NonExistentTimeError: 2002-04-07 02:30:00
```

**Comment by micolous** [comment]
The exception is only thrown when is_dst=None.  My test was:

```diff
diff --git a/tests.py b/tests.py
index d4ae9ed..b000ebd 100644
--- a/tests.py
+++ b/tests.py
@@ -335,7 +335,7 @@ class TestDatetimeTZ(unittest.TestCase):
     self.assertEqual(d1.tzinfo, d3.tzinfo)
 
     # Creation from a datetime object
-    d4 = datetime.datetime.now()
+    d4 = datetime.datetime(2015,10,4,2,30)
     d4 = pytz.timezone("Australia/Sydney").localize(d4)
     d5 = datetime_tz.datetime_tz(d4)
     self.assertTrue(isinstance(d3, datetime_tz.datetime_tz))
```

This caused the tests to fail, because I think somewhere is_dst=False, and somewhere else is_dst=True.
